name: exercie1bonus

on:
  push:
    tags:
    - 'release*'

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VAR1: 111
    steps:
      - name: Step 1
        run: |
          echo $VAR1

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "le job précédent à échoué"
    
