name: exercice2

on:
 workflow_dispatch:

env:
  a: 12
  b: 22

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        if: $a > 0 && $b > 0
        run: |
          echo "La valeur de a est ${{ a }} et la valeur de b est ${{ b }}"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
